### ISSUE TITLE
can't start after restoring from backup

### ISSUE THREAD

**Issue by michalk-k** [hassio-addons/addon-unifi#115]
# Problem/Motivation

After restoring the controller from HA backup the Controller can't start. 
Backup has been created on RPi4 HA 0.115.x. 
Restored on new RPi4 HA 0.117.6, HassOS 5.5 (SSD boot). 
In first step all components has been restored except of Unify Controller. After making all up and running, and shuting down old Pi, I restored Unify Controller only.

note, backup contains Unifi Controller integration v.0.19.0

Logs (debug mode) shows as follows:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.19.0
 There is an update available for this add-on!
 Latest add-on version: 0.19.2
 Please consider upgrading as soon as possible.
 System: HassOS 5.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:16:21] INFO: Starting the UniFi Controller...
Exception in thread "SocketListener(a0d7b954-unifi-local-hass-io.local.)" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at javax.jmdns.impl.ServiceInfoImpl.decodeQualifiedNameMapForType(ServiceInfoImpl.java:291)
	at javax.jmdns.impl.JmDNSImpl.registerServiceType(JmDNSImpl.java:1074)
	at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1383)
	at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1412)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:60)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: timed out
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
I can update to latest integration version, but not sure if it helps.

**Comment by michalk-k** [comment]
Strange... today I did another try, restoring the same backup over non working integration.
And it started inspite of the same error in logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.19.0
 There is an update available for this add-on!
 Latest add-on version: 0.19.2
 Please consider upgrading as soon as possible.
 System: HassOS 5.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:56:25] INFO: Starting the UniFi Controller...
Exception in thread "SocketListener(a0d7b954-unifi-local-hass-io.local.)" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at javax.jmdns.impl.ServiceInfoImpl.decodeQualifiedNameMapForType(ServiceInfoImpl.java:291)
	at javax.jmdns.impl.JmDNSImpl.registerServiceType(JmDNSImpl.java:1074)
	at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1383)
	at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1412)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:60)
```

**Comment by BiasF** [comment]
same here can't start mein unifi controller after restore :/

**Comment by VDBBjorn** [comment]
I'm also experiencing a similar issue when trying to restore my backup, see logs:

<code>
[13:05:00] INFO: Starting the UniFi Controller...
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-15" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:177)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
	at com.ubnt.service.OoOO.Ö00000(Unknown Source)
	at com.ubnt.ace.Launcher$2.run(Unknown Source)
[13:07:35] INFO: Starting the UniFi Controller...
</code>

**Comment by MoBluey** [comment]
I'm also experiencing the same issue. As well as being presented with the setup wizard every so often. I've had to setup as a new site then import site to get it working when needed. Pain in the arse but I make changes then export a new backup for use next time...

**Comment by pataar** [comment]
Export only the settings, not the data over time. That did the trick for me.

**Comment by MoBluey** [comment]
> Backup only the settings, not the data over time. That did the trick for me.

Legend! That worked like a gem. Thanks mate!
