### ISSUE TITLE
dB clearing acording to Ubiquiti Support not possible in HassIO 

### ISSUE THREAD

**Issue by QbaF** [hassio-addons/addon-unifi#175]
# Problem/Motivation

In Controller Logs (UI), found ERRORS.
```
[2021-03-21T13:40:43,213] <inform_stat-1> ERROR dev - Error in DeviceManager.processStat() com.mongodb.MongoQueryException: Query failed with error code 10334 and error message 'BSONObj size: -286331154 (0xEEEEEEEE) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: ObjectId('600486d266cc1024b7186c46')' on server localhost:27117 at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:131) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:295) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:212) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.FindOperation$1.call(FindOperation.java:525) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.FindOperation$1.call(FindOperation.java:510) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:435) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:408) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.FindOperation.execute(FindOperation.java:510) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.operation.FindOperation.execute(FindOperation.java:81) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.Mongo.execute(Mongo.java:836) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.Mongo$2.execute(Mongo.java:823) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870) ~[mongo-java-driver-3.4.3.jar:?] at com.mongodb.DBCursor.hasNext(DBCursor.java:142) ~[mongo-java-driver-3.4.3.jar:?] at com.ubnt.service.system.OooO.Ò00000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.O0o0.Ò00000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.O0o0.OO0000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.O0o0.ôÔ0000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.O0o0.o00000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.i.o00000(Unknown Source) ~[ace.jar:?] at com.ubnt.service.devmgr.o0o0$_o.run(Unknown Source) [ace.jar:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

Ubiquiti Support ask for cleaning db according to [this article](https://help.ui.com/hc/en-us/articles/360006634094-UniFi-Network-Controller-Repairing-Database-Issues-on-the-UniFi-Controller)

Unfortunately it is not possible for Home Assistant OS
```
➜  /tmp mongod --dbpath /usr/lib/unifi/data/db --smallfiles --logpath /usr/lib/unifi/logs/server.log --repair
zsh: command not found: mongod
➜  /tmp
```

## Expected behavior

Possibility to clear Unifi Controller dB

## Actual behavior

command not found

**Comment by frenck** [comment]
That is correct, that is not possible.

**Comment by QbaF** [comment]
Let me understand - it is not an issue that there are errors while using addon and we can not solve it even though producent tell us why and how?

**Comment by frenck** [comment]
Repairing is a bug upstream, should not be needed. Please report your issue with Ubiquity.

**Comment by QbaF** [comment]
It is not necessary Ubiquiti bug. Sudden lost of power is common databases problem.
