### ISSUE TITLE
After firmware upgrade of UniFi devices set-inform url will change to internal docker IP address

### ISSUE THREAD

**Issue by MyKEcz** [hassio-addons/addon-unifi#20]
# Problem/Motivation

Inform url was automatically changed from real IP of HASS.io to the Internal Docker IP address of HASS.io addon.

## Expected behavior

Keep Inform URL as it is during manual/initial configuration (for example if IP address of HASS.io connected to the network has IP address 192.168.1.100).

> Connect to the managed IP of the device via SSH > info > Status: Connected (http://192.168.1.100:8080/inform)

## Actual behavior

I experienced this behavior during firmware upgrade of UniFi devices (AP and Switch). USG Inform URLwas never changed, only AP and Switch were changed.

Connect to the managed IP of the device via SSH:
> info
Status: Unknown[11] (http://172.30.33.3:8080/inform)
> set-inform http://192.168.1.100:8080/inform

Device was connected back to UniFi Controller.

## Steps to reproduce

Mostly after auto-firmware upgrade or it happen once during Addon upgrade.

**Comment by sinclairpaul** [comment]
There is an option in the controller settings to override the inform host.  I would guess that the application defaults to its local IP, I'll confirm it works when I get round to updating the firmware.

**Comment by frenck** [comment]
This is documented...

**Comment by sinclairpaul** [comment]
I should check before commenting 😀

**Comment by hwikene** [comment]
I keep getting these errors after updating. 
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.int.OoOO]: Factory method 'autoOptimizer' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deviceManager' defined in com.ubnt.service.AppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.oOOO.O0OO]: Factory method 'deviceManager' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteManager' defined in com.ubnt.service.AppContext: Invocation of init method failed; nested exception is com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 16 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deviceManager' defined in com.ubnt.service.AppContext: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.oOOO.O0OO]: Factory method 'deviceManager' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteManager' defined in com.ubnt.service.AppContext: Invocation of init method failed; nested exception is com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.deviceManager(<generated>)
	at com.ubnt.service.AppContext.autoOptimizer(Unknown Source)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.CGLIB$autoOptimizer$25(<generated>)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0$$FastClassBySpringCGLIB$$8fc75dd4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.autoOptimizer(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 17 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ubnt.service.oOOO.O0OO]: Factory method 'deviceManager' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteManager' defined in com.ubnt.service.AppContext: Invocation of init method failed; nested exception is com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 40 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteManager' defined in com.ubnt.service.AppContext: Invocation of init method failed; nested exception is com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:394)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.siteManager(<generated>)
	at com.ubnt.service.AppContext.deviceManager(Unknown Source)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.CGLIB$deviceManager$28(<generated>)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0$$FastClassBySpringCGLIB$$8fc75dd4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$ebaa07d0.deviceManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 41 more
Caused by: com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224)
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:289)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:212)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:525)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:510)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:435)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:408)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:510)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
	at com.ubnt.service.OoOO.returnsuper.o00000(Unknown Source)
	at com.ubnt.service.OoOO.returnsuper.o00000(Unknown Source)
	at com.ubnt.service.OoOO.ifsuper.Ò00000(Unknown Source)
	at com.ubnt.service.OoOO.O.o00000(Unknown Source)
	at com.ubnt.service.OoOO.O.ÔO0000(Unknown Source)
	at com.ubnt.service.OoOO.O.ÔÓ0000(Unknown Source)
	at com.ubnt.service.OoOO.O.afterPropertiesSet(Unknown Source)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
	... 61 more
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 15, 2019 8:45:02 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
```

**Comment by frenck** [comment]
2 things in this issue.

1) During the upgrade, the INFORM may get lost. Currently, it is unknown why. Nevertheless, it can easily be fixed by setting it again. More information about setting it can be found in the add-on documentation.

2) The error: `INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)`
Is not pretty, but can be safely ignored. The add-on will function normally.
