### ISSUE TITLE
Controller offline after 1.0 update

### ISSUE THREAD

**Issue by Sku1ly** [hassio-addons/addon-unifi#248]
# Problem/Motivation

Upgraded to 1.0. No breaking changes affect me. Unable to access unifi controller via unifi.ui.com
See XML error or offline

## Expected behavior

Log into Unifi controller to manage network

## Actual behavior

Controller offline

## Steps to reproduce

Upgraded to 1.0

## Proposed changes

No idea. Error below

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2021.8.5
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:39:51] INFO: Starting the UniFi Controller...
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.B.if(Unknown Source)
	at com.ubnt.service.ooOO.Óo0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more`
```

**Comment by Bounties1337** [comment]
Same here. Log shows INFO: Starting the Unifi Controller....
However, I am not able to request the webpage nor to go over add-on "open webui"... .

Odd.. Please help.

**Comment by frenck** [comment]
duplicate of #249
