### ISSUE TITLE
Error on config restore, also not able to create new config

### ISSUE THREAD

**Issue by gurkburk76** [hassio-addons/addon-unifi#268]
# Problem/Motivation
Does not seem to work to read back a backup config.

> (Why the issue was filed)

## Expected behavior
To load the backup and go on with my life.

> (What you expected to happen)

## Actual behavior
Seems to spit out an error/config is not fully restored.

I also tried to create a clean unifi controller by making a local account and pretty much skipping all info in hope that i would be able to load my config there, for some reason it won't create a new config, no real reason given, just a red popup with something like "unable to create" or something like that

> (What actually happened)
reloaded config, got an error i think, was not able to log into the controller

## Steps to reproduce
load config, check log, try to logon, fail.

> (How can someone else make/see it happen)

## Proposed changes
not sure.

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by gurkburk76** [comment]
So i'm having issues with the unifi controller, i have a 6.2.26 setup that i've exported a config from that i'm trying to move to/as an add-on to ha, when i start the plugin and restore the backup it seems to go ok but it does not let me in (i'm using a local only admin account on the controller) i do see this in the log so it might have something to do with it.   org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-15" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
    at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:177)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1123)
    at com.ubnt.service.ooOO.return(Unknown Source)
    at com.ubnt.ace.Launcher$2.run(Unknown Source)
[11:19:52] INFO: Starting the UniFi Controller...
i also tried to create a clean unifi controller by making a local account and pretty much skipping all info in hope that i would be able to load my config there, for some reason it won't create a new config, no real reason given, just a red popup with something like "unable to create" or something like that.


I do not want to deal with "cloud accounts" and would like to stick to my local admin account, not sure if that's a part of the problem but i thought i'de mentioned it.

**Comment by gurkburk76** [comment]
some more logs from HA after a restart:

21-09-06 10:43:34 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/unifi/amd64 with version 1.0.0
21-09-06 10:43:34 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-5581' coro=<HomeAssistantWebSocket.async_send_command() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:106> exception=TypeError('Received message 257:None is not str')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 134, in async_send_command
    return await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 46, in async_send_command
    response = await self.client.receive_json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str

**Comment by gurkburk76** [comment]
## System Health

version | core-2021.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.61
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4804
Installed Version | 1.15.2
Stage | running
Available Repositories | 882
Installed Repositories | 23

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.3
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 14.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.104.3), Mosquitto broker (6.0.1), Grafana (7.0.1), Duck DNS (1.12.5), InfluxDB (4.2.1), Visual Studio Code (3.6.2), A better presence (1.2.0), ESPHome (2021.8.2), TasmoAdmin (0.15.0), DahuaVTO2MQTT (1.0.2), UniFi Controller (1.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 13
views | 18
mode | yaml

</details>

**Comment by gurkburk76** [comment]
seems like it somehow didn't like the first config i got when doing site migration, tried again and it was less fuzzy.
Closing....
