### ISSUE TITLE
Addon crashes with exception in thread SocketListener 

### ISSUE THREAD

**Issue by ghazlewood** [hassio-addons/addon-unifi#82]
# Problem/Motivation

Addon crashes a few seconds after startup

## Expected behavior

The addon doesn’t crash

## Actual behavior

Logs 

----------------
 Hass.io Add-on: UniFi Controller
 Manage your UniFi network using a web browser
-----------------------------------------------------------
 Add-on version: 0.15.0
 You are running the latest version of this add-on.
 System: null  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.8
 Home Assistant Supervisor: 219
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] unifi.sh: executing... 
Importing keystore /tmp/tmp.DFHt2m5Sjp to /usr/lib/unifi/data/keystore...

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
[cont-init.d] unifi.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:02:35] INFO: Starting the UniFi Controller...
Exception in thread "SocketListener(a0d7b954-unifi-local-hass-io.local.)" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at javax.jmdns.impl.ServiceInfoImpl.decodeQualifiedNameMapForType(ServiceInfoImpl.java:291)
	at javax.jmdns.impl.JmDNSImpl.registerServiceType(JmDNSImpl.java:1074)
	at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1383)
	at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1412)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:60)

Config

Web port is on 8087 not 8080 but everything else is out of the box. Configuration was working perfectly until recently but I’m not sure what changed to stop it running

## Steps to reproduce

Start the addon

**Comment by ghazlewood** [comment]
I used the CLI to restart the DNS service (`ha dns restart`) and the problem went away
